POST https://co-make1.herokuapp.com/api/Register
Content-Type: application/json

{
"username": "Amin", "password": "Amin"
}

###
POST https://co-make1.herokuapp.com/api/Login
Content-Type: application/json

# {
# "username": "user", "password": "user"
# }
{
"username": "admin", "password": "admin"
}
###
GET https://co-make1.herokuapp.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoyLCJ1c2VybmFtZSI6ImFkbWluIiwiZmlyc3RfbmFtZSI6IldlbGNvbWUgQWRtaW4iLCJpc19hZG1pbiI6MSwiaWF0IjoxNTkyNTAwODEwLCJleHAiOjE1OTI2NzM2MTB9.3K0csLT0gfDOxbfqNG6lxRf1C3bxEukEzMcnV5TS5OY
